server:
  port: 8080

twilio:
  config:
    accountSid: ${TWILIO_ACCOUNT_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: "+1XXXXXXXXXX"

sendgrid:
  apiKey: ${SENDGRID_API_KEY}

firebase:
  credentialsPath: /path/to/service-account.json
  projectId: your-project-id

# Uncomment to use Resend (and add the adapter dependency)
#resend:
#  apiKey: ${RESEND_API_KEY}
#  defaultFrom: noreply@example.com